# Generated by Django 3.2.13 on 2022-11-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comcomment',
            old_name='review',
            new_name='community',
        ),
    ]
