# Generated by Django 3.2.13 on 2022-11-02 02:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='city',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='avatars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
