# Generated by Django 3.2.13 on 2022-11-02 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_auto_20221102_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='themes',
            field=models.CharField(choices=[('힐링', '힐링'), ('액티비티', '액티비티'), ('맛집', '맛집'), ('숙박', '숙박'), ('체험', '체험')], max_length=4),
        ),
    ]
