# Generated by Django 3.2.13 on 2022-11-02 04:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20221102_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='avatars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
