# Generated by Django 3.2.13 on 2022-11-02 04:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20221102_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='places'),
        ),
        migrations.AlterField(
            model_name='place',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='places'),
        ),
    ]
