# Generated by Django 3.2.13 on 2022-11-02 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0005_auto_20221102_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Spot',
        ),
    ]
