# Generated by Django 3.2.13 on 2022-11-01 05:14

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subtitle', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
        ),
    ]
