# Generated by Django 3.2.13 on 2022-11-07 07:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='media/'),
        ),
    ]
