# Generated by Django 3.2.13 on 2022-11-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
