# Generated by Django 3.2.13 on 2022-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='review_city', to='places.City'),
        ),
    ]
