# Generated by Django 3.2.13 on 2022-11-02 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(choices=[(None, '선택'), ('서울', '서울'), ('제주', '제주'), ('부산', '부산')], default='선택', max_length=2),
        ),
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='review_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
